[metadata]  # Basic metadata: name and version of the game. Emulator doesn't use this data, but this can be used by launchers in the future
name = "Test Game"
version = "v1.0"

[settings]  # Settings for the runner
ram_size = 2000  # Number of bytes program uses for the RAM
stack_size = 1000  # Number of bytes program uses for the stack

[resources]  # External stuff that's used by your game
entry = "source.vea"  # Path (relative to the directory's root) of the source code. By convention this should be source.vea
palette = "palette.pal"  # Same as above, but for your palette and convention is palette.pal
